import type { Teacher, Subject, EducationLevel, Location, Review } from "./types"

export const educationLevels: EducationLevel[] = [
  {
    id: "1",
    name: "التأسيس",
    subjects: ["اللغة العربية", "اللغة الإنجليزية", "الرياضيات", "القرآن الكريم"],
  },
  {
    id: "2",
    name: "المرحلة الابتدائية",
    subjects: [
      "الرياضيات",
      "العلوم",
      "اللغة العربية",
      "اللغة الإنجليزية",
      "الدراسات الاجتماعية",
      "التربية الدينية",
      "الحاسب الآلي",
    ],
  },
  {
    id: "3",
    name: "المرحلة الإعدادية",
    subjects: [
      "الرياضيات",
      "العلوم",
      "اللغة العربية",
      "اللغة الإنجليزية",
      "الدراسات الاجتماعية",
      "التربية الدينية",
      "الحاسب الآلي",
      "اللغة الفرنسية",
    ],
  },
  {
    id: "4",
    name: "المرحلة الثانوية",
    subjects: [
      "الرياضيات",
      "الفيزياء",
      "الكيمياء",
      "الأحياء",
      "اللغة العربية",
      "اللغة الإنجليزية",
      "التاريخ",
      "الجغرافيا",
      "الفلسفة والمنطق",
      "علم النفس والاجتماع",
      "اللغة الفرنسية",
      "اللغة الألمانية",
      "اللغة الإيطالية",
      "الاقتصاد والإحصاء",
      "الجيولوجيا وعلوم البيئة",
    ],
  },
  {
    id: "5",
    name: "القرآن الكريم والتجويد",
    subjects: ["القرآن الكريم", "التجويد", "التفسير", "الحديث الشريف", "الفقه"],
  },
  {
    id: "6",
    name: "التعليم الجامعي",
    subjects: [
      "الرياضيات المتقدمة",
      "الفيزياء المتقدمة",
      "الكيمياء المتقدمة",
      "الأحياء المتقدمة",
      "الهندسة",
      "الطب",
      "الصيدلة",
      "الحقوق",
      "التجارة",
    ],
  },
]

export const subjects: Subject[] = [
  // مواد التأسيس
  {
    id: "1",
    name: "اللغة العربية",
    educationLevels: ["التأسيس", "المرحلة الابتدائية", "المرحلة الإعدادية", "المرحلة الثانوية"],
  },
  {
    id: "2",
    name: "اللغة الإنجليزية",
    educationLevels: ["التأسيس", "المرحلة الابتدائية", "المرحلة الإعدادية", "المرحلة الثانوية"],
  },
  {
    id: "3",
    name: "الرياضيات",
    educationLevels: ["التأسيس", "المرحلة الابتدائية", "المرحلة الإعدادية", "المرحلة الثانوية"],
  },

  // مواد القرآن
  { id: "4", name: "القرآن الكريم", educationLevels: ["التأسيس", "القرآن الكريم والتجويد"] },
  { id: "5", name: "التجويد", educationLevels: ["القرآن الكريم والتجويد"] },
  { id: "6", name: "التفسير", educationLevels: ["القرآن الكريم والتجويد"] },
  { id: "7", name: "الحديث الشريف", educationLevels: ["القرآن الكريم والتجويد"] },
  { id: "8", name: "الفقه", educationLevels: ["القرآن الكريم والتجويد"] },

  // مواد المراحل الأساسية
  { id: "9", name: "العلوم", educationLevels: ["المرحلة الابتدائية", "المرحلة الإعدادية"] },
  { id: "10", name: "الدراسات الاجتماعية", educationLevels: ["المرحلة الابتدائية", "المرحلة الإعدادية"] },
  { id: "11", name: "التربية الدينية", educationLevels: ["المرحلة الابتدائية", "المرحلة الإعدادية"] },
  { id: "12", name: "الحاسب الآلي", educationLevels: ["المرحلة الابتدائية", "المرحلة الإعدادية"] },

  // مواد المرحلة الثانوية
  { id: "13", name: "الفيزياء", educationLevels: ["المرحلة الثانوية"] },
  { id: "14", name: "الكيمياء", educationLevels: ["المرحلة الثانوية"] },
  { id: "15", name: "الأحياء", educationLevels: ["المرحلة الثانوية"] },
  { id: "16", name: "التاريخ", educationLevels: ["المرحلة الثانوية"] },
  { id: "17", name: "الجغرافيا", educationLevels: ["المرحلة الثانوية"] },
  { id: "18", name: "الفلسفة والمنطق", educationLevels: ["المرحلة الثانوية"] },
  { id: "19", name: "علم النفس والاجتماع", educationLevels: ["المرحلة الثانوية"] },
  { id: "20", name: "اللغة الفرنسية", educationLevels: ["المرحلة الإعدادية", "المرحلة الثانوية"] },
  { id: "21", name: "اللغة الألمانية", educationLevels: ["المرحلة الثانوية"] },
  { id: "22", name: "اللغة الإيطالية", educationLevels: ["المرحلة الثانوية"] },
  { id: "23", name: "الاقتصاد والإحصاء", educationLevels: ["المرحلة الثانوية"] },
  { id: "24", name: "الجيولوجيا وعلوم البيئة", educationLevels: ["المرحلة الثانوية"] },

  // مواد جامعية
  { id: "25", name: "الرياضيات المتقدمة", educationLevels: ["التعليم الجامعي"] },
  { id: "26", name: "الفيزياء المتقدمة", educationLevels: ["التعليم الجامعي"] },
  { id: "27", name: "الكيمياء المتقدمة", educationLevels: ["التعليم الجامعي"] },
  { id: "28", name: "الأحياء المتقدمة", educationLevels: ["التعليم الجامعي"] },
  { id: "29", name: "الهندسة", educationLevels: ["التعليم الجامعي"] },
  { id: "30", name: "الطب", educationLevels: ["التعليم الجامعي"] },
  { id: "31", name: "الصيدلة", educationLevels: ["التعليم الجامعي"] },
  { id: "32", name: "الحقوق", educationLevels: ["التعليم الجامعي"] },
  { id: "33", name: "التجارة", educationLevels: ["التعليم الجامعي"] },
]

export const locations: Location[] = [
  { id: "1", name: "القاهرة", type: "city" },
  { id: "2", name: "الجيزة", type: "city" },
  { id: "3", name: "الإسكندرية", type: "city" },
  { id: "4", name: "أونلاين", type: "online" },
  { id: "5", name: "مدينة نصر", type: "area" },
  { id: "6", name: "المعادي", type: "area" },
  { id: "7", name: "الزمالك", type: "area" },
  { id: "8", name: "مصر الجديدة", type: "area" },
  { id: "9", name: "المهندسين", type: "area" },
  { id: "10", name: "الدقي", type: "area" },
  { id: "11", name: "شبرا", type: "area" },
  { id: "12", name: "المطرية", type: "area" },
  { id: "13", name: "حلوان", type: "area" },
  { id: "14", name: "المنيل", type: "area" },
  { id: "15", name: "العباسية", type: "area" },
  { id: "16", name: "الهرم", type: "area" },
  { id: "17", name: "فيصل", type: "area" },
  { id: "18", name: "6 أكتوبر", type: "city" },
  { id: "19", name: "الشيخ زايد", type: "area" },
  { id: "20", name: "التجمع الخامس", type: "area" },
]

// تحديث قاعدة البيانات لتكون أكثر دقة في الربط بين المراحل والمواد والمدرسين

// إضافة المزيد من المدرسين مع ربط دقيق للمواد والمراحل
export const teachers: Teacher[] = [
  // مدرسين التأسيس
  {
    id: "1",
    name: "أستاذة نورا عبد الله",
    image: "/images/teachers/teacher6.png",
    subjects: ["اللغة العربية", "اللغة الإنجليزية", "الرياضيات"],
    educationLevel: ["التأسيس"],
    locations: ["مدينة نصر", "المعادي", "أونلاين"],
    description: "متخصصة في تأسيس الأطفال في اللغات والرياضيات، حاصلة على دبلوم تربوي وخبرة 12 سنة",
    teachingMethod: "أستخدم الألعاب التعليمية والأنشطة التفاعلية لجذب انتباه الأطفال وتحبيبهم في التعلم",
    contactWhatsapp: "01234567895",
    contactEmail: "nora@example.com",
    rating: 4.9,
    reviewsCount: 28,
    isOnline: true,
    isApproved: true,
    joinDate: "2023-03-15",
  },
  {
    id: "2",
    name: "أستاذة سارة أحمد",
    image: "/images/teachers/teacher2.png",
    subjects: ["اللغة العربية", "القرآن الكريم"],
    educationLevel: ["التأسيس"],
    locations: ["القاهرة", "الجيزة", "أونلاين"],
    description: "معلمة تأسيس متخصصة في اللغة العربية والقرآن الكريم للأطفال",
    teachingMethod: "أستخدم القصص والحكايات لتعليم الحروف والكلمات مع حفظ القرآن بالتجويد",
    contactWhatsapp: "01234567896",
    contactEmail: "sara.ahmed@example.com",
    rating: 4.8,
    reviewsCount: 22,
    isOnline: true,
    isApproved: true,
    joinDate: "2023-04-01",
  },

  // مدرسين المرحلة الابتدائية
  {
    id: "3",
    name: "أستاذ محمد حسن",
    image: "/images/teachers/teacher3.png",
    subjects: ["الرياضيات", "العلوم"],
    educationLevel: ["المرحلة الابتدائية"],
    locations: ["الإسكندرية", "أونلاين"],
    description: "مدرس رياضيات وعلوم للمرحلة الابتدائية، خبرة 8 سنوات في تبسيط المفاهيم العلمية",
    teachingMethod: "أستخدم التجارب البسيطة والأمثلة العملية لتوضيح المفاهيم الرياضية والعلمية",
    contactWhatsapp: "01234567897",
    contactEmail: "mohamed.hassan@example.com",
    rating: 4.7,
    reviewsCount: 35,
    isOnline: true,
    isApproved: true,
    joinDate: "2023-02-10",
  },
  {
    id: "4",
    name: "أستاذة فاطمة علي",
    image: "/images/teachers/teacher4.png",
    subjects: ["اللغة الإنجليزية", "الحاسب الآلي"],
    educationLevel: ["المرحلة الابتدائية"],
    locations: ["مدينة نصر", "التجمع الخامس", "أونلاين"],
    description: "مدرسة لغة إنجليزية وحاسب آلي للمرحلة الابتدائية، متخصصة في التعليم التفاعلي",
    teachingMethod: "أستخدم الألعاب التعليمية والبرامج التفاعلية لتعليم اللغة والحاسوب",
    contactWhatsapp: "01234567898",
    contactEmail: "fatma.ali@example.com",
    rating: 4.6,
    reviewsCount: 29,
    isOnline: true,
    isApproved: true,
    joinDate: "2023-05-15",
  },
  {
    id: "5",
    name: "أستاذة مريم محمود",
    image: "/images/teachers/teacher5.png",
    subjects: ["اللغة العربية", "الدراسات الاجتماعية", "التربية الدينية"],
    educationLevel: ["المرحلة الابتدائية"],
    locations: ["الجيزة", "الهرم", "أونلاين"],
    description: "مدرسة لغة عربية ودراسات اجتماعية، حاصلة على ليسانس آداب وخبرة 10 سنوات",
    teachingMethod: "أربط الدروس بالتاريخ والجغرافيا المصرية لتسهيل الحفظ والفهم",
    contactWhatsapp: "01234567899",
    contactEmail: "mariam.mahmoud@example.com",
    rating: 4.8,
    reviewsCount: 31,
    isOnline: true,
    isApproved: true,
    joinDate: "2023-01-20",
  },

  // مدرسين المرحلة الإعدادية
  {
    id: "6",
    name: "أستاذ أحمد محمد",
    image: "/images/teachers/teacher1.png",
    subjects: ["الرياضيات", "العلوم"],
    educationLevel: ["المرحلة الإعدادية"],
    locations: ["القاهرة", "العباسية", "أونلاين"],
    description: "مدرس رياضيات وعلوم للمرحلة الإعدادية، حاصل على بكالوريوس علوم رياضة",
    teachingMethod: "أركز على حل المسائل العملية وربط الرياضيات بالعلوم الطبيعية",
    contactWhatsapp: "01234567800",
    contactEmail: "ahmed.mohamed@example.com",
    rating: 4.7,
    reviewsCount: 42,
    isOnline: true,
    isApproved: true,
    joinDate: "2022-09-15",
  },
  {
    id: "7",
    name: "أستاذة هدى سالم",
    image: "/images/teachers/teacher7.png",
    subjects: ["اللغة الإنجليزية", "اللغة الفرنسية"],
    educationLevel: ["المرحلة الإعدادية"],
    locations: ["الزمالك", "مصر الجديدة", "أونلاين"],
    description: "مدرسة لغات للمرحلة الإعدادية، حاصلة على ليسانس ألسن وخبرة 9 سنوات",
    teachingMethod: "أستخدم المحادثة والأفلام التعليمية لتطوير مهارات اللغة",
    contactWhatsapp: "01234567801",
    contactEmail: "hoda.salem@example.com",
    rating: 4.8,
    reviewsCount: 27,
    isOnline: true,
    isApproved: true,
    joinDate: "2023-03-08",
  },
  {
    id: "8",
    name: "أستاذ كريم فتحي",
    image: "/images/teachers/teacher8.png",
    subjects: ["الدراسات الاجتماعية", "التربية الدينية"],
    educationLevel: ["المرحلة الإعدادية"],
    locations: ["المعادي", "حلوان", "أونلاين"],
    description: "مدرس دراسات اجتماعية وتربية دينية، خريج دار العلوم وخبرة 11 سنة",
    teachingMethod: "أستخدم الخرائط والصور التاريخية مع ربط الأحداث بالواقع المعاصر",
    contactWhatsapp: "01234567802",
    contactEmail: "karim.fathy@example.com",
    rating: 4.9,
    reviewsCount: 38,
    isOnline: true,
    isApproved: true,
    joinDate: "2022-11-12",
  },

  // مدرسين المرحلة الثانوية - علمي
  {
    id: "9",
    name: "دكتور محمد رضا",
    image: "/images/teachers/teacher9.png",
    subjects: ["الرياضيات", "الفيزياء"],
    educationLevel: ["المرحلة الثانوية"],
    locations: ["القاهرة", "الجيزة", "أونلاين"],
    description: "دكتور في الفيزياء النظرية، خبرة 15 سنة في تدريس الثانوية العامة",
    teachingMethod: "أربط القوانين الفيزيائية بالرياضيات مع التطبيقات العملية والتجارب",
    contactWhatsapp: "01234567803",
    contactEmail: "mohamed.reda@example.com",
    rating: 4.9,
    reviewsCount: 56,
    isOnline: true,
    isApproved: true,
    joinDate: "2022-08-01",
  },
  {
    id: "10",
    name: "دكتورة سارة محمود",
    image: "/images/teachers/teacher10.png",
    subjects: ["الكيمياء", "الأحياء"],
    educationLevel: ["المرحلة الثانوية"],
    locations: ["الجيزة", "المهندسين", "أونلاين"],
    description: "دكتوراه في الكيمياء الحيوية، خبرة 12 سنة في تدريس العلوم للثانوية العامة",
    teachingMethod: "أربط الكيمياء بالأحياء مع التجارب المعملية والنماذج التوضيحية",
    contactWhatsapp: "01234567804",
    contactEmail: "sara.mahmoud@example.com",
    rating: 4.8,
    reviewsCount: 48,
    isOnline: true,
    isApproved: true,
    joinDate: "2022-10-15",
  },
  {
    id: "11",
    name: "دكتورة منى إبراهيم",
    image: "/images/teachers/teacher11.png",
    subjects: ["الجيولوجيا وعلوم البيئة"],
    educationLevel: ["المرحلة الثانوية"],
    locations: ["شبرا", "المطرية", "أونلاين"],
    description: "دكتوراه في الجيولوجيا، متخصصة في علوم الأرض والبيئة للثانوية العامة",
    teachingMethod: "أستخدم العينات الطبيعية والرحلات الاستطلاعية لتعليم علوم الأرض",
    contactWhatsapp: "01234567805",
    contactEmail: "mona.ibrahim@example.com",
    rating: 4.7,
    reviewsCount: 33,
    isOnline: true,
    isApproved: true,
    joinDate: "2023-01-10",
  },

  // مدرسين المرحلة الثانوية - أدبي
  {
    id: "12",
    name: "أستاذ عمر الشافعي",
    image: "/images/teachers/teacher12.png",
    subjects: ["التاريخ", "الجغرافيا"],
    educationLevel: ["المرحلة الثانوية"],
    locations: ["القاهرة", "العباسية", "أونلاين"],
    description: "أستاذ تاريخ وجغرافيا، حاصل على ماجستير في التاريخ الحديث وخبرة 18 سنة",
    teachingMethod: "أستخدم الخرائط التفاعلية والأفلام الوثائقية لتوضيح الأحداث التاريخية",
    contactWhatsapp: "01234567806",
    contactEmail: "omar.shafei@example.com",
    rating: 4.9,
    reviewsCount: 52,
    isOnline: true,
    isApproved: true,
    joinDate: "2022-07-20",
  },
  {
    id: "13",
    name: "دكتورة رانيا حسن",
    image: "/images/teachers/teacher13.png",
    subjects: ["الفلسفة والمنطق", "علم النفس والاجتماع"],
    educationLevel: ["المرحلة الثانوية"],
    locations: ["المعادي", "حلوان", "أونلاين"],
    description: "دكتوراه في الفلسفة، متخصصة في تبسيط المفاهيم الفلسفية والنفسية",
    teachingMethod: "أستخدم الأمثلة الواقعية والحوارات الفلسفية لتوضيح المفاهيم المجردة",
    contactWhatsapp: "01234567807",
    contactEmail: "rania.hassan@example.com",
    rating: 4.8,
    reviewsCount: 41,
    isOnline: true,
    isApproved: true,
    joinDate: "2022-12-05",
  },
  {
    id: "14",
    name: "أستاذ محمود سعد",
    image: "/images/teachers/teacher14.png",
    subjects: ["الاقتصاد والإحصاء"],
    educationLevel: ["المرحلة الثانوية"],
    locations: ["الهرم", "فيصل", "أونلاين"],
    description: "أستاذ اقتصاد وإحصاء، حاصل على ماجستير في الاقتصاد التطبيقي وخبرة 13 سنة",
    teachingMethod: "أربط النظريات الاقتصادية بالواقع المصري مع استخدام الرسوم البيانية",
    contactWhatsapp: "01234567808",
    contactEmail: "mahmoud.saad@example.com",
    rating: 4.7,
    reviewsCount: 36,
    isOnline: true,
    isApproved: true,
    joinDate: "2023-02-18",
  },

  // مدرسين اللغات
  {
    id: "15",
    name: "أستاذة مريم فؤاد",
    image: "/images/teachers/teacher15.png",
    subjects: ["اللغة الفرنسية"],
    educationLevel: ["المرحلة الإعدادية", "المرحلة الثانوية"],
    locations: ["الزمالك", "مصر الجديدة", "أونلاين"],
    description: "دكتوراه في اللغة الفرنسية، مترجمة معتمدة وخبرة 14 سنة في التدريس",
    teachingMethod: "أستخدم الأفلام والأغاني الفرنسية مع التركيز على المحادثة العملية",
    contactWhatsapp: "01234567809",
    contactEmail: "mariam.fouad@example.com",
    rating: 4.8,
    reviewsCount: 44,
    isOnline: true,
    isApproved: true,
    joinDate: "2022-09-30",
  },
  {
    id: "16",
    name: "أستاذ كريم محمد",
    image: "/images/teachers/teacher16.png",
    subjects: ["اللغة الألمانية"],
    educationLevel: ["المرحلة الثانوية"],
    locations: ["الزمالك", "المنيل", "أونلاين"],
    description: "حاصل على شهادة Goethe C2، مترجم ومدرس لغة ألمانية بخبرة 10 سنوات",
    teachingMethod: "أركز على القواعد والمحادثة مع استخدام الثقافة الألمانية في التعليم",
    contactWhatsapp: "01234567810",
    contactEmail: "karim.mohamed@example.com",
    rating: 4.6,
    reviewsCount: 28,
    isOnline: true,
    isApproved: true,
    joinDate: "2023-04-12",
  },
  {
    id: "17",
    name: "أستاذة إيمان سالم",
    image: "/images/teachers/teacher17.png",
    subjects: ["اللغة الإيطالية"],
    educationLevel: ["المرحلة الثانوية"],
    locations: ["مصر الجديدة", "العباسية", "أونلاين"],
    description: "خريجة الجامعة الأمريكية، متخصصة في اللغة الإيطالية وخبرة 8 سنوات",
    teachingMethod: "أستخدم الموسيقى والأفلام الإيطالية لتعليم اللغة بطريقة ممتعة",
    contactWhatsapp: "01234567811",
    contactEmail: "iman.salem@example.com",
    rating: 4.5,
    reviewsCount: 22,
    isOnline: true,
    isApproved: true,
    joinDate: "2023-06-08",
  },

  // مدرسين القرآن الكريم والتجويد
  {
    id: "18",
    name: "الشيخ عبد الرحمن أحمد",
    image: "/images/teachers/teacher18.png",
    subjects: ["القرآن الكريم", "التجويد"],
    educationLevel: ["القرآن الكريم والتجويد"],
    locations: ["القاهرة", "الجيزة", "أونلاين"],
    description: "حافظ للقرآن الكريم ومجاز في القراءات العشر، خريج الأزهر الشريف",
    teachingMethod: "أركز على التطبيق العملي لأحكام التجويد مع الحفظ المتقن",
    contactWhatsapp: "01234567812",
    contactEmail: "abdelrahman.ahmed@example.com",
    rating: 4.9,
    reviewsCount: 67,
    isOnline: true,
    isApproved: true,
    joinDate: "2022-06-15",
  },
  {
    id: "19",
    name: "الشيخ محمد عبد الله",
    image: "/images/teachers/teacher19.png",
    subjects: ["التفسير", "الحديث الشريف", "الفقه"],
    educationLevel: ["القرآن الكريم والتجويد"],
    locations: ["القاهرة", "شبرا", "أونلاين"],
    description: "عالم أزهري، متخصص في التفسير والحديث والفقه الإسلامي",
    teachingMethod: "أربط النصوص الشرعية بالواقع المعاصر مع التطبيق العملي",
    contactWhatsapp: "01234567813",
    contactEmail: "mohamed.abdullah@example.com",
    rating: 4.8,
    reviewsCount: 54,
    isOnline: true,
    isApproved: true,
    joinDate: "2022-08-20",
  },

  // مدرسين التعليم الجامعي
  {
    id: "20",
    name: "دكتور أحمد رضا",
    image: "/images/teachers/teacher20.png",
    subjects: ["الطب", "الأحياء المتقدمة"],
    educationLevel: ["التعليم الجامعي"],
    locations: ["القاهرة", "الجيزة", "أونلاين"],
    description: "طبيب وأستاذ جامعي، دكتوراه في الطب الباطني وخبرة 16 سنة",
    teachingMethod: "أركز على الحالات السريرية والتطبيق العملي مع الصور التوضيحية",
    contactWhatsapp: "01234567814",
    contactEmail: "ahmed.reda.md@example.com",
    rating: 4.9,
    reviewsCount: 73,
    isOnline: true,
    isApproved: true,
    joinDate: "2022-05-10",
  },
]

// تحديث التقييمات لتشمل المدرسين الجدد
export const reviews: Review[] = [
  {
    id: "1",
    teacherId: "1",
    studentName: "سارة أحمد",
    rating: 5,
    comment: "مدرس ممتاز، شرحه واضح ومفهوم ويستخدم أمثلة عملية رائعة",
    date: "2024-01-15",
  },
  {
    id: "2",
    teacherId: "1",
    studentName: "علي محمد",
    rating: 4,
    comment: "استفدت كثيراً من دروسه في الفيزياء، أسلوبه مميز",
    date: "2024-01-10",
  },
  {
    id: "3",
    teacherId: "4",
    studentName: "أحمد حسن",
    rating: 5,
    comment: "الشيخ عبد الرحمن معلم قرآن ممتاز، صبور ومتقن ويحفظني بطريقة سهلة",
    date: "2024-01-20",
  },
  {
    id: "4",
    teacherId: "5",
    studentName: "مريم علي",
    rating: 5,
    comment: "دكتورة سارة تشرح الكيمياء بطريقة سهلة ومفهومة مع تجارب رائعة",
    date: "2024-01-18",
  },
  {
    id: "5",
    teacherId: "2",
    studentName: "فاطمة محمود",
    rating: 5,
    comment: "أستاذة فاطمة تجعل اللغة العربية ممتعة وسهلة الفهم",
    date: "2024-01-22",
  },
  {
    id: "6",
    teacherId: "3",
    studentName: "يوسف أحمد",
    rating: 4,
    comment: "تحسن مستواي في الإنجليزية كثيراً معه، خاصة في المحادثة",
    date: "2024-01-25",
  },
  {
    id: "7",
    teacherId: "6",
    studentName: "ليلى حسن",
    rating: 5,
    comment: "ابنتي تحب الدروس معها، تستخدم ألعاب تعليمية رائعة",
    date: "2024-01-28",
  },
  {
    id: "8",
    teacherId: "7",
    studentName: "كريم محمد",
    rating: 5,
    comment: "مهندس خالد يربط الرياضيات بالهندسة بطريقة عملية ممتازة",
    date: "2024-01-30",
  },
  {
    id: "9",
    teacherId: "8",
    studentName: "نورهان علي",
    rating: 4,
    comment: "تعلمت الفرنسية بسرعة معها، أسلوبها تفاعلي ومميز",
    date: "2024-02-01",
  },
  {
    id: "10",
    teacherId: "9",
    studentName: "محمد سعد",
    rating: 5,
    comment: "أستاذ عمر يجعل التاريخ مثير ومشوق، لا أنسى دروسه أبداً",
    date: "2024-02-03",
  },
]
